const computerNetworksBank = [
  // Theory (1-25)
  { question: "What defines the communication rules on the WWW?", options: ["HTTP", "MAC", "IP", "DNS"], answer: 0 },
  { question: "Which device operates primarily at the Network Layer?", options: ["Switch", "Hub", "Router", "Repeater"], answer: 2 },
  { question: "What is the bit length of an IPv4 address?", options: ["16", "32", "64", "128"], answer: 1 },
  { question: "Which OSI layer ensures reliable data delivery?", options: ["Data Link", "Network", "Transport", "Application"], answer: 2 },
  { question: "Standard port for HTTPS?", options: ["80", "21", "443", "22"], answer: 2 },
  { question: "Which protocol resolves IP to MAC?", options: ["ARP", "DHCP", "DNS", "ICMP"], answer: 0 },
  { question: "Typical MTU size of Ethernet frame?", options: ["512", "1024", "1500", "3000"], answer: 2 },
  { question: "Topology connecting all devices to a central hub?", options: ["Ring", "Bus", "Star", "Mesh"], answer: 2 },
  { question: "Address hardcoded into a NIC?", options: ["Logical", "IP", "MAC", "Port"], answer: 2 },
  { question: "Connectionless Transport Layer protocol?", options: ["TCP", "UDP", "SPX", "IPSec"], answer: 1 },
  { question: "Bit length of IPv6?", options: ["32", "64", "128", "256"], answer: 2 },
  { question: "OSI layer for encryption?", options: ["Application", "Presentation", "Session", "Transport"], answer: 1 },
  { question: "Protocol for sending outbound emails?", options: ["IMAP", "POP3", "SMTP", "FTP"], answer: 2 },
  { question: "Primary function of a firewall?", options: ["Assign IP", "Filter traffic", "Amplify WiFi", "Host web"], answer: 1 },
  { question: "Link-state routing protocol?", options: ["RIP", "BGP", "OSPF", "EIGRP"], answer: 2 },
  { question: "IPv4 loopback address?", options: ["192.168.1.1", "10.0.0.0", "255.255.255.255", "127.0.0.1"], answer: 3 },
  { question: "Default port for SSH?", options: ["21", "22", "23", "25"], answer: 1 },
  { question: "Purpose of subnetting?", options: ["Combine ISPs", "Divide network", "Encrypt", "Replace routers"], answer: 1 },
  { question: "Attenuation means?", options: ["Signal loss", "Interference", "Compression", "Duplication"], answer: 0 },
  { question: "Wi-Fi 6 standard?", options: ["802.11b", "802.11n", "802.11ac", "802.11ax"], answer: 3 },
  { question: "Combining multiple signals into one?", options: ["Modulation", "Multiplexing", "Encapsulation", "Broadcasting"], answer: 1 },
  { question: "OSI layer handling voltage?", options: ["Data Link", "Physical", "Network", "Transport"], answer: 1 },
  { question: "Core routing protocol of the Internet?", options: ["OSPF", "RIP", "IS-IS", "BGP"], answer: 3 },
  { question: "Attack overwhelming a network with traffic?", options: ["Phishing", "MITM", "DDoS", "SQLi"], answer: 2 },
  { question: "Layer 2 Switch principle?", options: ["Broadcasting", "Forwarding by MAC", "Routing by IP", "Blocking ports"], answer: 1 },
  // Lab (26-50)
  { question: "CLI tool tracking packet paths?", options: ["ping", "tracert", "netstat", "nslookup"], answer: 1 },
  { question: "Windows command for MAC address?", options: ["ipconfig", "ipconfig /all", "macconfig", "getmac"], answer: 1 },
  { question: "Packet capture standard software?", options: ["Nmap", "Putty", "Wireshark", "Packet Tracer"], answer: 2 },
  { question: "Cable to connect router to switch?", options: ["Crossover", "Straight-through", "Rollover", "Fiber"], answer: 1 },
  { question: "Cisco link active color?", options: ["Red", "Amber", "Green", "Blue"], answer: 2 },
  { question: "DNS query command?", options: ["nslookup", "arp -a", "route print", "nbtstat"], answer: 0 },
  { question: "View Windows routing table?", options: ["ipconfig /route", "route print", "netstat -r", "Both B and C"], answer: 3 },
  { question: "Ping relies on which protocol?", options: ["TCP", "UDP", "ICMP", "IGMP"], answer: 2 },
  { question: "Twisted-pair cable connector?", options: ["RJ-11", "RJ-45", "BNC", "LC"], answer: 1 },
  { question: "Class C default subnet mask?", options: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"], answer: 2 },
  { question: "Release DHCP IP command?", options: ["ipconfig /renew", "ipconfig /release", "ipconfig /flush", "ipconfig /drop"], answer: 1 },
  { question: "Cisco IOS interface config mode?", options: ["User", "Privileged", "Global", "Interface"], answer: 3 },
  { question: "View active TCP connections?", options: ["ping", "tracert", "netstat", "arp"], answer: 2 },
  { question: "Turn on Cisco interface command?", options: ["start", "enable port", "no shutdown", "interface up"], answer: 2 },
  { question: "Save Cisco config command?", options: ["save", "write memory", "commit", "store"], answer: 1 },
  { question: "Wireshark filter for web traffic?", options: ["port 80", "http", "tcp.port == 80", "All of the above"], answer: 3 },
  { question: "Clear Windows DNS cache?", options: ["ipconfig /cleardns", "ipconfig /flushdns", "netsh reset", "dns --clear"], answer: 1 },
  { question: "Red lightning bolt in Packet Tracer?", options: ["Fiber", "Auto connection", "Serial", "Console"], answer: 1 },
  { question: "Port scanning tool?", options: ["Ping", "Nmap", "Traceroute", "Netcat"], answer: 1 },
  { question: "View ARP cache command?", options: ["arp -a", "ipconfig /arp", "mac -list", "netstat -mac"], answer: 0 },
  { question: "Test internal TCP/IP stack?", options: ["ping gateway", "ping 8.8.8.8", "ping 127.0.0.1", "ping 0.0.0.0"], answer: 2 },
  { question: "Tool for UTP into patch panel?", options: ["Crimper", "Stripper", "Punch-down tool", "Multimeter"], answer: 2 },
  { question: "Cable tester swapped Tx/Rx result?", options: ["Short", "Open", "Split", "Crossed"], answer: 3 },
  { question: "Cisco brief interface status?", options: ["show ip int brief", "show int", "show route", "show run"], answer: 0 },
  { question: "Which OSI layer is responsible for routing?", options: ["Layer 1", "Layer 2", "Layer 3", "Layer 4"], answer: 2 }
];

const pythonAIBank = [
  // Theory (1-25)
  { question: "Reward/punishment ML approach?", options: ["Supervised", "Unsupervised", "Reinforcement", "Transfer"], answer: 2 },
  { question: "Purpose of a Loss Function?", options: ["Speed up", "Measure error", "Define architecture", "Format data"], answer: 1 },
  { question: "Tokenization in NLP means?", options: ["Encrypting", "Breaking text to words", "Translating", "Speech to text"], answer: 1 },
  { question: "Transformers solve what RNN problem?", options: ["Memory", "Images", "Vanishing gradient", "Timeouts"], answer: 2 },
  { question: "RAG stands for?", options: ["Random Access Gen", "Retrieval-Augmented Gen", "Recurrent AI Graph", "Recursive Algo"], answer: 1 },
  { question: "Purpose of ReLU?", options: ["Download", "Introduce non-linearity", "Compress", "Save"], answer: 1 },
  { question: "Pooling layer in CNN does what?", options: ["Add colors", "Reduce dimensions", "Increase res", "Translate"], answer: 1 },
  { question: "Gradient Descent aims to?", options: ["Maximize rate", "Find global max", "Minimize loss", "Sort data"], answer: 2 },
  { question: "Overfitting means?", options: ["Good on train, poor on test", "Too small", "Fast training", "Too large dataset"], answer: 0 },
  { question: "Best metric for imbalanced data?", options: ["Accuracy", "F1-Score", "MSE", "R-Squared"], answer: 1 },
  { question: "Word Embeddings are?", options: ["Font style", "Dense vector representations", "Spell-check", "Dictionary"], answer: 1 },
  { question: "LLM 'Temperature' controls?", options: ["Heat", "Length", "Randomness/creativity", "Speed"], answer: 2 },
  { question: "Unsupervised algorithm?", options: ["Linear Reg", "Logistic Reg", "K-Means", "Random Forest"], answer: 2 },
  { question: "Zero-Shot Prompting means?", options: ["Zero instructions", "No examples provided", "Untrained model", "Empty prompt"], answer: 1 },
  { question: "Pandas DataFrame feature/variable is a?", options: ["Row", "Column", "Index", "Cell"], answer: 1 },
  { question: "AI Bias refers to?", options: ["Intercept", "Unfair discrimination", "Error difference", "Learning rate"], answer: 1 },
  { question: "Primary use of Scikit-learn?", options: ["Web servers", "Classical ML algorithms", "UIs", "SQL"], answer: 1 },
  { question: "Simplest artificial neuron?", options: ["Deep layer", "GPU", "Perceptron", "Metric"], answer: 2 },
  { question: "TF-IDF stands for?", options: ["Text Format", "Term Freq - Inverse Doc Freq", "Total Features", "True False"], answer: 1 },
  { question: "Fine-tuning means?", options: ["Delete memory", "Adapt to specific task", "Change language", "Reduce size"], answer: 1 },
  { question: "Ensemble method?", options: ["Decision Tree", "SVM", "Random Forest", "KNN"], answer: 2 },
  { question: "AI Hallucination means?", options: ["Images", "Confident false response", "Server crash", "Bad prompt"], answer: 1 },
  { question: "Transformer core mechanism?", options: ["Recursion", "Backprop", "Self-Attention", "Convolution"], answer: 2 },
  { question: "Validation set use?", options: ["Final report", "Tuning hyperparameters", "Core weights", "Downloading"], answer: 1 },
  { question: "LLM using external tools?", options: ["Data Augment", "Agentic AI", "Dimensionality", "Clustering"], answer: 1 },
  // Lab (26-50)
  { question: "Load CSV into pandas?", options: ["read()", "pd.read_csv()", "load()", "open()"], answer: 1 },
  { question: "Return first 5 DataFrame rows?", options: ["start()", "top()", "head()", "first()"], answer: 2 },
  { question: "Scikit-learn data split?", options: ["split()", "train_test_split()", "DataSplitter()", "divide()"], answer: 1 },
  { question: "Instantiate Linear Regression?", options: ["LinearRegression()", "new Linear", "create()", "Scikit.Linear()"], answer: 0 },
  { question: "Train model method?", options: ["train()", "fit()", "learn()", "predict()"], answer: 1 },
  { question: "Generate predictions?", options: ["predict()", "test()", "infer()", "evaluate()"], answer: 0 },
  { question: "Matplotlib scatter plot?", options: ["plot()", "scatter()", "graph()", "points()"], answer: 1 },
  { question: "Drop NaN in pandas?", options: ["drop_missing()", "remove_nan()", "dropna()", "clean()"], answer: 2 },
  { question: "Securely pass API key?", options: ["Hardcode", "os.getenv()", "URL", "Input"], answer: 1 },
  { question: "Library for RAG pipelines?", options: ["Django", "LangChain", "PyGame", "Requests"], answer: 1 },
  { question: "Convert categorical to numerical?", options: ["hist()", "describe()", "OneHotEncoder", "StandardScaler"], answer: 2 },
  { question: "LLM message history format?", options: ["String", "CSV", "List of role/content dicts", "Binary"], answer: 2 },
  { question: "Calculate classification accuracy?", options: ["accuracy_score()", "score()", "accuracy()", "correct()"], answer: 0 },
  { question: "Scale numerical features?", options: ["MinMax()", "StandardScaler()", "Normalizer()", "Scale()"], answer: 1 },
  { question: "Define K-Means clusters?", options: ["clusters=5", "n_clusters=5", "k=5", "num=5"], answer: 1 },
  { question: "DataFrame summary stats?", options: ["info()", "stats()", "summary()", "describe()"], answer: 3 },
  { question: "Matrix data structure in Python?", options: ["List", "Dict", "NumPy Array", "Tuple"], answer: 2 },
  { question: "Import Pandas?", options: ["import pandas as p", "import pandas", "import pandas as pd", "from pandas"], answer: 2 },
  { question: "Stack Keras layers linearly?", options: ["Linear()", "Sequential()", "Stack()", "Network()"], answer: 1 },
  { question: "Add Dense Keras layer?", options: ["model.add(Dense(64))", "append()", "layer()", "insert()"], answer: 0 },
  { question: "Scikit-learn metrics module?", options: ["preprocessing", "metrics", "model_selection", "ensemble"], answer: 1 },
  { question: "Install external packages?", options: ["python install", "pip install", "apt-get", "npm install"], answer: 1 },
  { question: "System prompt in OpenAI?", options: ["role: 'system'", "URL param", "model name", "temperature"], answer: 0 },
  { question: "Extract 'Price' column?", options: ["get('Price')", "df['Price']", "PriceColumn", "df(Price)"], answer: 1 },
  { question: "Print DataFrame shape?", options: ["size", "dimensions", "shape", "len"], answer: 2 }
];

const dbmsBank = [
  // Theory (1-25)
  { question: "ACID 'A' stands for?", options: ["Accuracy", "Atomicity", "Availability", "Aggregation"], answer: 1 },
  { question: "Key linking two tables?", options: ["Primary", "Candidate", "Foreign", "Super"], answer: 2 },
  { question: "Process reducing redundancy?", options: ["Indexing", "Normalization", "Hashing", "Replication"], answer: 1 },
  { question: "ER diagram attribute shape?", options: ["Rectangle", "Diamond", "Ellipse", "Triangle"], answer: 2 },
  { question: "Which is a DDL command?", options: ["INSERT", "UPDATE", "CREATE", "SELECT"], answer: 2 },
  { question: "A 'Tuple' is?", options: ["Column", "Table", "Row", "Index"], answer: 2 },
  { question: "Normal form removing partial dependency?", options: ["1NF", "2NF", "3NF", "BCNF"], answer: 1 },
  { question: "Database view is?", options: ["Physical copy", "Virtual table", "Index", "Backup"], answer: 1 },
  { question: "Filter after aggregation?", options: ["WHERE", "ORDER", "HAVING", "GROUP"], answer: 2 },
  { question: "Join returning only matched rows?", options: ["Left", "Right", "Full", "Inner"], answer: 3 },
  { question: "Primary purpose of indexing?", options: ["Encrypt", "Speed retrieval", "Delete data", "Constraints"], answer: 1 },
  { question: "Which is a DML command?", options: ["GRANT", "DROP", "DELETE", "ALTER"], answer: 2 },
  { question: "COMMIT does what?", options: ["Undo", "Save permanently", "Start new", "Lock"], answer: 1 },
  { question: "Deadlock means?", options: ["Crash", "Indefinite waiting for locks", "Slow query", "Disk full"], answer: 1 },
  { question: "NoSQL storing key-value?", options: ["Document", "Graph", "Key-Value", "Column"], answer: 2 },
  { question: "Schema means?", options: ["Data stored", "Logical structure", "Program", "Hardware"], answer: 1 },
  { question: "Constraint preventing NULL?", options: ["UNIQUE", "NOT NULL", "CHECK", "DEFAULT"], answer: 1 },
  { question: "TRUNCATE vs DELETE?", options: ["Types", "Truncate clears all fast", "WHERE usage", "No diff"], answer: 1 },
  { question: "Stored Procedure is?", options: ["Temp table", "Precompiled SQL block", "Log", "GUI"], answer: 1 },
  { question: "Combines columns of relations?", options: ["Selection", "Projection", "Union", "Cross Join"], answer: 3 },
  { question: "Trigger is?", options: ["UI Button", "Auto-executing SQL on event", "Backup", "Index"], answer: 1 },
  { question: "Normal form removing transitive dependency?", options: ["1NF", "2NF", "3NF", "BCNF"], answer: 2 },
  { question: "DCL means?", options: ["Data Control", "Data Create", "Database Core", "Data Command"], answer: 0 },
  { question: "Example of 1-to-many?", options: ["Student-ID", "Author-Books", "Student-Course", "Person-Passport"], answer: 1 },
  { question: "Data dictionary is?", options: ["Manual", "Passwords", "Metadata repository", "Keywords"], answer: 2 },
  // Lab (26-50)
  { question: "Select name and age?", options: ["SELECT name, age", "GET name", "FETCH", "PULL"], answer: 0 },
  { question: "Salary > 50000 query?", options: ["WHERE salary > 50000", "IF salary", "HAVING salary", "SELECT salary"], answer: 0 },
  { question: "Insert new record?", options: ["ADD", "INSERT INTO", "UPDATE", "CREATE ROW"], answer: 1 },
  { question: "Update status to Active?", options: ["UPDATE FROM", "MODIFY SET", "UPDATE SET", "CHANGE"], answer: 2 },
  { question: "Delete old logs?", options: ["REMOVE", "DELETE FROM", "DROP", "ERASE"], answer: 1 },
  { question: "Add new column?", options: ["UPDATE ADD", "ALTER TABLE ADD", "MODIFY INSERT", "ADD COLUMN"], answer: 1 },
  { question: "Count records?", options: ["SUM(*)", "TOTAL(*)", "COUNT(*)", "NUMBER(*)"], answer: 2 },
  { question: "Highest price?", options: ["MAX(price)", "TOP(price)", "HIGHEST", "MAXIMUM"], answer: 0 },
  { question: "Sort descending?", options: ["DOWN", "SORT DESC", "ORDER BY DESC", "GROUP DESC"], answer: 2 },
  { question: "Starts with 'A'?", options: ["LIKE 'A%'", "LIKE '%A'", "='A*'", "STARTSWITH"], answer: 0 },
  { question: "Distinct values?", options: ["UNIQUE", "DISTINCT", "DIFFERENT", "NO DUPES"], answer: 1 },
  { question: "Condition for GROUP BY?", options: ["WHERE", "ORDER", "HAVING", "CONDITION"], answer: 2 },
  { question: "ID is 1, 2, or 3?", options: ["= 1,2,3", "IN (1,2,3)", "BETWEEN", "Both B and C"], answer: 3 },
  { question: "Inner Join syntax?", options: ["JOIN ON", "WHERE =", "INNER JOIN ON", "All above"], answer: 3 },
  { question: "Create index syntax?", options: ["MAKE INDEX", "CREATE INDEX", "ADD INDEX", "SET INDEX"], answer: 1 },
  { question: "MySQL first 5 records?", options: ["TOP 5", "LIMIT 5", "FETCH 5", "FIRST 5"], answer: 1 },
  { question: "Age between 20 and 30?", options: [">=20 AND <=30", "BETWEEN 20 AND 30", "Both A/B", "IN(20,30)"], answer: 2 },
  { question: "Revoke SELECT?", options: ["REMOVE", "REVOKE SELECT ON", "DELETE", "DENY"], answer: 1 },
  { question: "Create View?", options: ["CREATE VIEW AS", "MAKE VIEW", "GENERATE", "VIEW AS"], answer: 0 },
  { question: "Permanently remove table?", options: ["DELETE TABLE", "TRUNCATE TABLE", "DROP TABLE", "REMOVE TABLE"], answer: 2 },
  { question: "Rename table?", options: ["RENAME TO", "ALTER RENAME TO", "Both A/B", "CHANGE"], answer: 2 },
  { question: "Contains 'smith'?", options: ["'smith%'", "'%smith%'", "'%smith'", "'*smith*'"], answer: 1 },
  { question: "Primary key purpose?", options: ["Unique/Not Null", "Auto-increment", "Encrypt", "Link Cloud"], answer: 0 },
  { question: "Delete table data but keep structure?", options: ["DROP", "DELETE", "TRUNCATE", "REMOVE"], answer: 2 },
  { question: "Default JOIN type?", options: ["LEFT", "RIGHT", "FULL OUTER", "INNER"], answer: 3 }
];

window.subjectCatalog = [
  { id: "networks", title: "Computer Networks", bank: computerNetworksBank },
  { id: "python-ai", title: "Python & AI", bank: pythonAIBank },
  { id: "dbms", title: "Database Systems", bank: dbmsBank }
];